[build]
  command = "npm run docs:build"
  publish = "docs/.vitepress/dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "24"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
[context.production.environment]
  NODE_ENV = "production"